{% set name = "keplergl" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1762c4212f177843884ad51f74e06ee3efe58ea3711d0327b6aa99ccbed52815

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37 or s390x]

requirements:
  host:
    - python
    - setuptools
    - pip
    - jupyter-packaging
    - wheel
  run:
    - python
    - ipywidgets >=7.0.0,<8
    - traittypes >=0.2.1
    - pandas >=0.23.0
    - geopandas >=0.5.0
    - shapely >=1.6.4.post2

test:
  requires:
    - pip
  imports:
    - keplergl
  commands:
    - pip check

about:
  home: https://github.com/keplergl/kepler.gl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Kepler.gl for Jupyter
  description: |
    This is a simple jupyter widget for kepler.gl, an advanced geospatial
    visualization tool, to render large-scale interactive maps.
  doc_url: https://docs.kepler.gl/docs/keplergl-jupyter
  dev_url: https://github.com/keplergl/kepler.gl/tree/master/bindings/kepler.gl-jupyter

extra:
  recipe-maintainers:
    - lixun910
    - heshan0131
